# The PublicBodyCategories structure works like this:
# [
#   "Main category name",
#       [ "tag_to_use_as_category", "Sub category title", "sentence that can describes things in this subcategory" ],
#       [ "another_tag", "Second sub category title", "another descriptive sentence for things in this subcategory"],
#   "Another main category name",
#       [ "another_tag_2", "Another sub category title", "another descriptive sentence"]
# ])
#
# DO NOT EDIT THIS FILE! It should be overridden in a custom theme.
# See doc/THEMES.md for more info

PublicBodyCategories.add(:he, [
    "תחומים",
        [ "security", "בטחון", "בטחון" ],
        [ "law", "חוק ומשפט", "חוק ומשפט"],
        [ "economy", "כלכלה", "כלכלה"],
        [ "transportation", "תחבורה", "תחבורה"],
        [ "education", "חינוך", "חינוך"],
        [ "religion", "דת", "דת"],
        [ "culture", "תרבות", "תרבות"],
        [ "communication", "תקשורת", "תקשורת"],
        [ "sport", "ספורט", "ספורט"],
        [ "welfare", "רווחה", "רווחה"],
    "אזורים",
        [ "north", "צפון", "צפון"],
        [ "center", "מרכז", "מרכז"],
        [ "south", "דרום", "דרום"]
])
